export default [
  {
    name: "Calgary",
    local_names: {
      uk: "Калґарі",
      it: "Calgary",
      pt: "Calgary",
      es: "Calgary",
      ar: "كالجاري",
      en: "Calgary",
      de: "Calgary",
      cr: "ᐅᑑᐢᑿᓂᕽ",
      fr: "Calgary",
      ru: "Калгари",
      eo: "Kalgario",
      zh: "卡尔加里",
      fa: "کلگری",
    },
    lat: 51.0460954,
    lon: -114.065465,
    country: "CA",
    state: "Alberta",
  },
  {
    name: "Calgary",
    local_names: {
      en: "Calgary",
      gd: "Cala Ghearraidh",
    },
    lat: 56.5789085,
    lon: -6.2767608,
    country: "GB",
    state: "Scotland",
  },
  {
    name: "Calgary",
    lat: 31.6174004,
    lon: -94.1193622,
    country: "US",
    state: "Texas",
  },
  {
    name: "Calgary",
    lat: -29.6921629,
    lon: 148.3796087,
    country: "AU",
    state: "New South Wales",
  },
];
